# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Nativer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Nativer
  pod 'Firebase/Core'
  pod 'Firebase/Database'
 

  target 'NativerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


