# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Nativer' do 

  
  rn_path = '../node_modules/react-native'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
  'Core',
  'RCTActionSheet',
  'RCTAnimation',
  'RCTGeolocation',
  'RCTImage',
  'RCTLinkingIOS',
  'RCTNetwork',
  'RCTSettings',
  'RCTText',
  'RCTVibration',
  'RCTWebSocket'
  ]

  # Pods for Nativer
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
 






end


